<?php
/**
 * Created by PhpStorm.
 * User: yuxiang
 * Date: 2017/2/7
 * Time: 19:34
 */
namespace Admin\Controller;


class SeoWebAccountController extends CommonController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 账户资料
     */
    public function update(){
        $userid = session('zzcms_adm_userid');
        $condition = array('id'=>$userid);
        $usernameRes = M('admin')->where($condition)->select();
        $username = $usernameRes[0]['username'];
        $this->assign("username",$username);
        $this->assign("type","账户资料");
        $this->display();
    }

    /**
     * 修改密码
     */
    public function UpdateSecrect(){
        $this->display();
    }
}

?>