<?php
/**
 * Created by PhpStorm.
 * User: yuxiang
 * Date: 2017/2/7
 * Time: 19:41
 */
namespace Admin\Controller;


class SeoWebAdminController extends CommonController  {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 网站添加
     */
    public function add(){
        $this->display();
    }

    /**
     * 网站管理
     */
    public function ListInfo(){
        $this->display();
    }
}