<?php
/**
 * Created by PhpStorm.
 * User: yuxiang
 * Date: 2016/12/31
 * Time: 22:40
 * Description: 网站设置
 */
namespace Admin\Controller;

use Common\Lib\Category;
use Think\Controller;

class WebSettingController extends Controller {
//    public function _initialize()
//    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//    }

    public function index()
    {
        $pid = I('get.id','','htmlspecialchars');
        if(empty($pid)){
            $pid = 0;
        }
        $condition['topid'] = $pid;
        $condition['status'] = 1;
        $menu = M('menu')->where(array('status' => 1))->order('sort,id')->select();
        if (empty($menu)) {
            $menu = array();
        }
        foreach ($menu as $k => $v) {
            $menu_c[] = $v;
        }
        $submenu = M('menu')->where($condition)->order('sort,id')->select();
        foreach ($submenu as $k => $v) {
            $submenu_c[] = $v;
        }
        $this->assign('pid',$pid);
        $this->assign('submenu',Category::toLayer($submenu_c,'child',$pid));
        $this->assign('menu', Category::toLayer($menu_c));
        $this->display();
    }

    public function KeySearch(){
        if(IS_POST){
            $data = I('post.', '');
            $keyWordArr = $data['searchname'];
            $arr = explode("|", $keyWordArr);
            $listinfo = array();
            $cnt = 0;
            $serverPrice = new AgentAdminController();
            foreach ($arr as $key) {
                $priceresult = $serverPrice->seachzhanprice($key);
                $listinfo[$cnt]['keyword'] = $key;
                $listinfo[$cnt]['baidu1'] = $priceresult['baidu1'];
                $listinfo[$cnt]['baidumobile1'] = $priceresult['baidumobile1'];
                $listinfo[$cnt]['sogou1'] = $priceresult['sogou1'];
                $listinfo[$cnt]['haosou1'] = $priceresult['haosou1'];
                $listinfo[$cnt]['shenma1'] = $priceresult['shenma1'];
                $cnt = $cnt + 1;
            }
            $listinfo = json_encode($listinfo, JSON_UNESCAPED_UNICODE);
            return show_tip(1, '搜索成功', null, U('KeySearch', array('listinfo' => $listinfo)));
        }else{
            $listinfoget = $_GET['listinfo'];
            $listinfo = json_decode($listinfoget,true);
            $this->assign('listinfo',$listinfo);
            $this->display();
        }
    }
}
?>

